spring.application.name=demo
# for https
server.forward-headers-strategy=framework 
spring.datasource.url = jdbc:mysql://localhost:3306/SocialSift?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
jwt.secret=vYp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7w!z%C*F-JaNd
jwt.expiration=3600000